/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-11-07 19:12:12 UTC)
 * on 2017-12-21 at 07:37:53 UTC 
 * Modify at your own risk.
 */

package challenge.rt.medibus.mani.data.source.remote.myApi;

import challenge.rt.medibus.mani.data.source.remote.myApi.model.CollectionResponseSalesRep;
import challenge.rt.medibus.mani.data.source.remote.myApi.model.CollectionResponseTaskDetail;
import challenge.rt.medibus.mani.data.source.remote.myApi.model.MyBean;
import challenge.rt.medibus.mani.data.source.remote.myApi.model.SalesRep;
import challenge.rt.medibus.mani.data.source.remote.myApi.model.TaskDetail;

/**
 * Service definition for MyApi (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link MyApiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class MyApi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.23.0 of the myApi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myApplicationId.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "myApi/v1/";

  /**
   * The default encoded batch path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.23
   */
  public static final String DEFAULT_BATCH_PATH = "batch";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public MyApi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  MyApi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "insertSalesRep".
   *
   * This request holds the parameters needed by the myApi server.  After setting any optional
   * parameters, call the {@link InsertSalesRep#execute()} method to invoke the remote operation.
   *
   * @param content the {@link SalesRep}
   * @return the request
   */
  public InsertSalesRep insertSalesRep(SalesRep content) throws java.io.IOException {
    InsertSalesRep result = new InsertSalesRep(content);
    initialize(result);
    return result;
  }

  public class InsertSalesRep extends MyApiRequest<SalesRep> {

    private static final String REST_PATH = "salesrep";

    /**
     * Create a request for the method "insertSalesRep".
     *
     * This request holds the parameters needed by the the myApi server.  After setting any optional
     * parameters, call the {@link InsertSalesRep#execute()} method to invoke the remote operation.
     * <p> {@link InsertSalesRep#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param content the {@link SalesRep}
     * @since 1.13
     */
    protected InsertSalesRep(SalesRep content) {
      super(MyApi.this, "POST", REST_PATH, content, SalesRep.class);
    }

    @Override
    public InsertSalesRep setAlt(java.lang.String alt) {
      return (InsertSalesRep) super.setAlt(alt);
    }

    @Override
    public InsertSalesRep setFields(java.lang.String fields) {
      return (InsertSalesRep) super.setFields(fields);
    }

    @Override
    public InsertSalesRep setKey(java.lang.String key) {
      return (InsertSalesRep) super.setKey(key);
    }

    @Override
    public InsertSalesRep setOauthToken(java.lang.String oauthToken) {
      return (InsertSalesRep) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertSalesRep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertSalesRep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertSalesRep setQuotaUser(java.lang.String quotaUser) {
      return (InsertSalesRep) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertSalesRep setUserIp(java.lang.String userIp) {
      return (InsertSalesRep) super.setUserIp(userIp);
    }

    @Override
    public InsertSalesRep set(String parameterName, Object value) {
      return (InsertSalesRep) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertTask".
   *
   * This request holds the parameters needed by the myApi server.  After setting any optional
   * parameters, call the {@link InsertTask#execute()} method to invoke the remote operation.
   *
   * @param content the {@link TaskDetail}
   * @return the request
   */
  public InsertTask insertTask(TaskDetail content) throws java.io.IOException {
    InsertTask result = new InsertTask(content);
    initialize(result);
    return result;
  }

  public class InsertTask extends MyApiRequest<TaskDetail> {

    private static final String REST_PATH = "taskdetail";

    /**
     * Create a request for the method "insertTask".
     *
     * This request holds the parameters needed by the the myApi server.  After setting any optional
     * parameters, call the {@link InsertTask#execute()} method to invoke the remote operation. <p>
     * {@link
     * InsertTask#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link TaskDetail}
     * @since 1.13
     */
    protected InsertTask(TaskDetail content) {
      super(MyApi.this, "POST", REST_PATH, content, TaskDetail.class);
    }

    @Override
    public InsertTask setAlt(java.lang.String alt) {
      return (InsertTask) super.setAlt(alt);
    }

    @Override
    public InsertTask setFields(java.lang.String fields) {
      return (InsertTask) super.setFields(fields);
    }

    @Override
    public InsertTask setKey(java.lang.String key) {
      return (InsertTask) super.setKey(key);
    }

    @Override
    public InsertTask setOauthToken(java.lang.String oauthToken) {
      return (InsertTask) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertTask setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertTask) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertTask setQuotaUser(java.lang.String quotaUser) {
      return (InsertTask) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertTask setUserIp(java.lang.String userIp) {
      return (InsertTask) super.setUserIp(userIp);
    }

    @Override
    public InsertTask set(String parameterName, Object value) {
      return (InsertTask) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listSalesRep".
   *
   * This request holds the parameters needed by the myApi server.  After setting any optional
   * parameters, call the {@link ListSalesRep#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListSalesRep listSalesRep() throws java.io.IOException {
    ListSalesRep result = new ListSalesRep();
    initialize(result);
    return result;
  }

  public class ListSalesRep extends MyApiRequest<CollectionResponseSalesRep> {

    private static final String REST_PATH = "salesrep";

    /**
     * Create a request for the method "listSalesRep".
     *
     * This request holds the parameters needed by the the myApi server.  After setting any optional
     * parameters, call the {@link ListSalesRep#execute()} method to invoke the remote operation. <p>
     * {@link
     * ListSalesRep#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListSalesRep() {
      super(MyApi.this, "GET", REST_PATH, null, CollectionResponseSalesRep.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListSalesRep setAlt(java.lang.String alt) {
      return (ListSalesRep) super.setAlt(alt);
    }

    @Override
    public ListSalesRep setFields(java.lang.String fields) {
      return (ListSalesRep) super.setFields(fields);
    }

    @Override
    public ListSalesRep setKey(java.lang.String key) {
      return (ListSalesRep) super.setKey(key);
    }

    @Override
    public ListSalesRep setOauthToken(java.lang.String oauthToken) {
      return (ListSalesRep) super.setOauthToken(oauthToken);
    }

    @Override
    public ListSalesRep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListSalesRep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListSalesRep setQuotaUser(java.lang.String quotaUser) {
      return (ListSalesRep) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListSalesRep setUserIp(java.lang.String userIp) {
      return (ListSalesRep) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public ListSalesRep setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListSalesRep setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public ListSalesRep set(String parameterName, Object value) {
      return (ListSalesRep) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTasks".
   *
   * This request holds the parameters needed by the myApi server.  After setting any optional
   * parameters, call the {@link ListTasks#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListTasks listTasks() throws java.io.IOException {
    ListTasks result = new ListTasks();
    initialize(result);
    return result;
  }

  public class ListTasks extends MyApiRequest<CollectionResponseTaskDetail> {

    private static final String REST_PATH = "taskdetail";

    /**
     * Create a request for the method "listTasks".
     *
     * This request holds the parameters needed by the the myApi server.  After setting any optional
     * parameters, call the {@link ListTasks#execute()} method to invoke the remote operation. <p>
     * {@link
     * ListTasks#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTasks() {
      super(MyApi.this, "GET", REST_PATH, null, CollectionResponseTaskDetail.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTasks setAlt(java.lang.String alt) {
      return (ListTasks) super.setAlt(alt);
    }

    @Override
    public ListTasks setFields(java.lang.String fields) {
      return (ListTasks) super.setFields(fields);
    }

    @Override
    public ListTasks setKey(java.lang.String key) {
      return (ListTasks) super.setKey(key);
    }

    @Override
    public ListTasks setOauthToken(java.lang.String oauthToken) {
      return (ListTasks) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTasks setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTasks) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTasks setQuotaUser(java.lang.String quotaUser) {
      return (ListTasks) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTasks setUserIp(java.lang.String userIp) {
      return (ListTasks) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer count;

    /**

     */
    public java.lang.Integer getCount() {
      return count;
    }

    public ListTasks setCount(java.lang.Integer count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTasks setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @Override
    public ListTasks set(String parameterName, Object value) {
      return (ListTasks) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeSalesRep".
   *
   * This request holds the parameters needed by the myApi server.  After setting any optional
   * parameters, call the {@link RemoveSalesRep#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveSalesRep removeSalesRep(java.lang.String id) throws java.io.IOException {
    RemoveSalesRep result = new RemoveSalesRep(id);
    initialize(result);
    return result;
  }

  public class RemoveSalesRep extends MyApiRequest<Void> {

    private static final String REST_PATH = "salesrep/{id}";

    /**
     * Create a request for the method "removeSalesRep".
     *
     * This request holds the parameters needed by the the myApi server.  After setting any optional
     * parameters, call the {@link RemoveSalesRep#execute()} method to invoke the remote operation.
     * <p> {@link RemoveSalesRep#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveSalesRep(java.lang.String id) {
      super(MyApi.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveSalesRep setAlt(java.lang.String alt) {
      return (RemoveSalesRep) super.setAlt(alt);
    }

    @Override
    public RemoveSalesRep setFields(java.lang.String fields) {
      return (RemoveSalesRep) super.setFields(fields);
    }

    @Override
    public RemoveSalesRep setKey(java.lang.String key) {
      return (RemoveSalesRep) super.setKey(key);
    }

    @Override
    public RemoveSalesRep setOauthToken(java.lang.String oauthToken) {
      return (RemoveSalesRep) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveSalesRep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveSalesRep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveSalesRep setQuotaUser(java.lang.String quotaUser) {
      return (RemoveSalesRep) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveSalesRep setUserIp(java.lang.String userIp) {
      return (RemoveSalesRep) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveSalesRep setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveSalesRep set(String parameterName, Object value) {
      return (RemoveSalesRep) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "sayHi1".
   *
   * This request holds the parameters needed by the myApi server.  After setting any optional
   * parameters, call the {@link SayHi1#execute()} method to invoke the remote operation.
   *
   * @param name
   * @return the request
   */
  public SayHi1 sayHi1(java.lang.String name) throws java.io.IOException {
    SayHi1 result = new SayHi1(name);
    initialize(result);
    return result;
  }

  public class SayHi1 extends MyApiRequest<MyBean> {

    private static final String REST_PATH = "sayHi/{name}";

    /**
     * Create a request for the method "sayHi1".
     *
     * This request holds the parameters needed by the the myApi server.  After setting any optional
     * parameters, call the {@link SayHi1#execute()} method to invoke the remote operation. <p> {@link
     * SayHi1#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param name
     * @since 1.13
     */
    protected SayHi1(java.lang.String name) {
      super(MyApi.this, "POST", REST_PATH, null, MyBean.class);
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
    }

    @Override
    public SayHi1 setAlt(java.lang.String alt) {
      return (SayHi1) super.setAlt(alt);
    }

    @Override
    public SayHi1 setFields(java.lang.String fields) {
      return (SayHi1) super.setFields(fields);
    }

    @Override
    public SayHi1 setKey(java.lang.String key) {
      return (SayHi1) super.setKey(key);
    }

    @Override
    public SayHi1 setOauthToken(java.lang.String oauthToken) {
      return (SayHi1) super.setOauthToken(oauthToken);
    }

    @Override
    public SayHi1 setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SayHi1) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SayHi1 setQuotaUser(java.lang.String quotaUser) {
      return (SayHi1) super.setQuotaUser(quotaUser);
    }

    @Override
    public SayHi1 setUserIp(java.lang.String userIp) {
      return (SayHi1) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public SayHi1 setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @Override
    public SayHi1 set(String parameterName, Object value) {
      return (SayHi1) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateSalesRep".
   *
   * This request holds the parameters needed by the myApi server.  After setting any optional
   * parameters, call the {@link UpdateSalesRep#execute()} method to invoke the remote operation.
   *
   * @param content the {@link SalesRep}
   * @return the request
   */
  public UpdateSalesRep updateSalesRep(SalesRep content) throws java.io.IOException {
    UpdateSalesRep result = new UpdateSalesRep(content);
    initialize(result);
    return result;
  }

  public class UpdateSalesRep extends MyApiRequest<SalesRep> {

    private static final String REST_PATH = "salesrep";

    /**
     * Create a request for the method "updateSalesRep".
     *
     * This request holds the parameters needed by the the myApi server.  After setting any optional
     * parameters, call the {@link UpdateSalesRep#execute()} method to invoke the remote operation.
     * <p> {@link UpdateSalesRep#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param content the {@link SalesRep}
     * @since 1.13
     */
    protected UpdateSalesRep(SalesRep content) {
      super(MyApi.this, "PUT", REST_PATH, content, SalesRep.class);
    }

    @Override
    public UpdateSalesRep setAlt(java.lang.String alt) {
      return (UpdateSalesRep) super.setAlt(alt);
    }

    @Override
    public UpdateSalesRep setFields(java.lang.String fields) {
      return (UpdateSalesRep) super.setFields(fields);
    }

    @Override
    public UpdateSalesRep setKey(java.lang.String key) {
      return (UpdateSalesRep) super.setKey(key);
    }

    @Override
    public UpdateSalesRep setOauthToken(java.lang.String oauthToken) {
      return (UpdateSalesRep) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSalesRep setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSalesRep) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSalesRep setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSalesRep) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSalesRep setUserIp(java.lang.String userIp) {
      return (UpdateSalesRep) super.setUserIp(userIp);
    }

    @Override
    public UpdateSalesRep set(String parameterName, Object value) {
      return (UpdateSalesRep) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link MyApi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
      setBatchPath(DEFAULT_BATCH_PATH);
    }

    /** Builds a new instance of {@link MyApi}. */
    @Override
    public MyApi build() {
      return new MyApi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setBatchPath(String batchPath) {
      return (Builder) super.setBatchPath(batchPath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link MyApiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setMyApiRequestInitializer(
        MyApiRequestInitializer myapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(myapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
