/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-11-07 19:12:12 UTC)
 * on 2017-12-21 at 07:37:53 UTC 
 * Modify at your own risk.
 */

package challenge.rt.medibus.mani.data.source.remote.myApi.model;

/**
 * Model definition for TaskDetail.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the myApi. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TaskDetail extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long endDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pharmacyName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String salesRep;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long startDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String taskDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String taskName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer taskStatus;

  public TaskDetail(challenge.rt.medibus.mani.data.TaskDetail taskDetail) {
    taskName = taskDetail.taskName;
    taskDescription = taskDetail.taskDescription;
    startDate = taskDetail.startDate;
    endDate = taskDetail.endDate;
    salesRep = taskDetail.salesRep;
    pharmacyName = taskDetail.pharmacyName;
  }

  public TaskDetail() {

  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEndDate() {
    return endDate;
  }

  /**
   * @param endDate endDate or {@code null} for none
   */
  public TaskDetail setEndDate(java.lang.Long endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPharmacyName() {
    return pharmacyName;
  }

  /**
   * @param pharmacyName pharmacyName or {@code null} for none
   */
  public TaskDetail setPharmacyName(java.lang.String pharmacyName) {
    this.pharmacyName = pharmacyName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSalesRep() {
    return salesRep;
  }

  /**
   * @param salesRep salesRep or {@code null} for none
   */
  public TaskDetail setSalesRep(java.lang.String salesRep) {
    this.salesRep = salesRep;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStartDate() {
    return startDate;
  }

  /**
   * @param startDate startDate or {@code null} for none
   */
  public TaskDetail setStartDate(java.lang.Long startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTaskDescription() {
    return taskDescription;
  }

  /**
   * @param taskDescription taskDescription or {@code null} for none
   */
  public TaskDetail setTaskDescription(java.lang.String taskDescription) {
    this.taskDescription = taskDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTaskName() {
    return taskName;
  }

  /**
   * @param taskName taskName or {@code null} for none
   */
  public TaskDetail setTaskName(java.lang.String taskName) {
    this.taskName = taskName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTaskStatus() {
    return taskStatus;
  }

  /**
   * @param taskStatus taskStatus or {@code null} for none
   */
  public TaskDetail setTaskStatus(java.lang.Integer taskStatus) {
    this.taskStatus = taskStatus;
    return this;
  }

  @Override
  public TaskDetail set(String fieldName, Object value) {
    return (TaskDetail) super.set(fieldName, value);
  }

  @Override
  public TaskDetail clone() {
    return (TaskDetail) super.clone();
  }

}
